Feature/notes list
mustafaberkaykaya/MVVMProjectBerkay pull request #10
Opened 2022-02-25 13:38 UTC by mustafaberkaykaya

2022-02-25 14:18 UTC, alihanaktay requested changes

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteRoute.swift
> +    func pushEdit(titleText: String, descriptionText: String, noteId: Int, type: DetailVCShowType)
zaten type yolluyoruz tek tek ayrı fonksiyon olmasına gerek yok

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +            saveNoteButton.addTarget(self, action: #selector(saveButtonTapped), for: .touchUpInside)
add target'o configure content içine alalım

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +            saveNoteButton.addTarget(self, action: #selector(updateButtonTapped), for: .touchUpInside)
add target'o configure content içine alalım

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +        setLocalize()
set localize'ı viewdidload içinden çağıralım

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +        let title = titleTextField.text ?? ""
validasyon koyabiliriz boşsa save etmesin

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +        let title = titleTextField.text ?? ""
validasyon koyabiliriz boşsa update etmesin

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +    private func saveButtonTapped() {
aslında tek action olup viewmodel içindeki type'da bunu handle edebilmemiz lazım ayrı ayrı actionlara gerek yok

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +            addDescriptionTextView()
bunlar tüm typelar için ortak dışarı alınabilir ve case içine sadece farklılıklar konabilir.

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +        descriptionTextView.delegate = self
delegate'i configure content içine alalım

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +
boşlukları silelim

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +    var type: DetailVCShowType = .add
bunlara gerek olmaması lazım direk viewmodel içinden alabilirsin birde controller içine tanımlamana gerek yok

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +        descriptionTextView.text = viewModel.descriptionText
bunları set localize içinde setleyelim

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/AddNote/AddNoteViewController.swift
> +}
textview delegate'i kullanmicaksak kaldırabiliriz

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +        notificationCenter.addObserver(self, selector: #selector(reloadData), name: .reloadDataNotification, object: nil)
notification'ı eğer will appeare'da tanımlarsak her ekran görüldüğünde tekrar notification kayıt edersin bug'a sebep olur bunu viewdidload'dan çağırdığımız ayrı bir extension bloğuna taşıyalım

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +        setLocalize()
set locallize'ı viewdidload üzerinden çağıralım ve boşluğu silelim

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +        refreshControl.addTarget(self, action: #selector(pullToRefreshValueChanged), for: .valueChanged)
configure content'e taşınmalı

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +            refreshControl.endRefreshing()
soldan indent düzeltelim

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +        cellItem = viewModel.cellItemAt(indexPath: indexPath)
tek satırda yazabiliriz

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +        cellItem = viewModel.cellItemAt(indexPath: indexPath)
tek satırda tanımlayalım

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewController.swift
> +        let noteID = self.viewModel.cellItems[indexPath.row].noteID
direk objeyi alıp bir değişkene setliyelim sonra o objenin titleText descriptionText ve noteID'sini alttaki fonsiyona setliyelim daha güzel bir görünüm olur

2022-02-25 14:18 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/NotesList/NotesListViewModel.swift
> +    func editRow(titleText: String, descriptionText: String, noteId: Int, type: DetailVCShowType)
bunlara gerek yok direk type üzerinden tek fonksiyona indirelim

2022-02-25 18:36 UTC, mustafaberkaykaya commented
İstenilen değişiklikleri yaptım

2022-02-28 07:29 UTC, alihanaktay approved these changes

2022-02-28 08:48 UTC, merged