Feature/profile
mustafaberkaykaya/MVVMProjectBerkay pull request #13
Opened 2022-03-01 13:11 UTC by mustafaberkaykaya

2022-03-01 14:05 UTC, alihanaktay requested changes

2022-03-01 14:05 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/Profile/ChangePassword/ChangePasswordViewController.swift
> +        guard validation.isValidPassword(retypeNewPassword) else { return }
Swift validator la validation ekliyelim

2022-03-01 14:05 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/Profile/ProfileViewController.swift
> +        viewModel.updateUser(userName: userName, email: email)
swift validator'la validation ekliyelim

2022-03-02 10:36 UTC, mustafaberkaykaya commented on NoteBerkayMvvm/Scenes/Notes/Profile/ChangePassword/ChangePasswordViewController.swift
> +        guard validation.isValidPassword(retypeNewPassword) else { return }
added

2022-03-02 10:47 UTC, mustafaberkaykaya commented on NoteBerkayMvvm/Scenes/Notes/Profile/ProfileViewController.swift
> +        viewModel.updateUser(userName: userName, email: email)
added

2022-03-02 10:59 UTC, alihanaktay requested changes

2022-03-02 10:59 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/Profile/ChangePassword/ChangePasswordViewController.swift
> +        if newPasswordTextField.text == newRePasswordTextField.text {
bunuda validation'a koyabiliriz swift validator'a

2022-03-02 10:59 UTC, alihanaktay commented on NoteBerkayMvvm/Scenes/Notes/Profile/ProfileViewController.swift
> +        validator.registerField(emailTextField, errorLabel: errorLabel, rules: [RequiredRule(), EmailRule()])
her save buttona bastığımda validator açıp register etmek yanlış bir yaklaşım ilk yüklemede bunları yapmak lazım

2022-03-02 11:11 UTC, mustafaberkaykaya commented on NoteBerkayMvvm/Scenes/Notes/Profile/ProfileViewController.swift
> +        validator.registerField(emailTextField, errorLabel: errorLabel, rules: [RequiredRule(), EmailRule()])
Değişiklik yaptım validatoru  şuan tanımladığım yer de bir sıkıntı var mı

2022-03-02 11:13 UTC, mustafaberkaykaya reviewed
Değişikliği yaptım . şuan validatoru tanımladığım yer en yukarısı. Bu yaklaşım yanlış mı ? Validator objesini başka bir yerde tanımlamak daha uygun mu olur ?

2022-03-02 11:18 UTC, alihanaktay commented
> Değişikliği yaptım . şuan validatoru tanımladığım yer en yukarısı. Bu yaklaşım yanlış mı ? Validator objesini başka bir yerde tanımlamak daha uygun mu olur ?

Bu şekilde doğru olmuş, birde passwordler aynımı karşılaştırmasınıda validator'e alalım

2022-03-02 11:25 UTC, mustafaberkaykaya commented on NoteBerkayMvvm/Scenes/Notes/Profile/ProfileViewController.swift
> +        validator.registerField(emailTextField, errorLabel: errorLabel, rules: [RequiredRule(), EmailRule()])
fixed

2022-03-02 11:25 UTC, mustafaberkaykaya commented on NoteBerkayMvvm/Scenes/Notes/Profile/ChangePassword/ChangePasswordViewController.swift
> +        if newPasswordTextField.text == newRePasswordTextField.text {
fixed

2022-03-02 11:27 UTC, alihanaktay approved these changes

2022-03-02 11:31 UTC, merged